_BASE_: MinVIS_R50_clip.yaml
MODEL:
  META_ARCHITECTURE: "DVIS_online"
  MASK_FORMER:
    TRANSFORMER_DECODER_NAME: "VideoMultiScaleMaskedTransformerDecoder_dvis_clip"
  TRACKER:
    NOISE_MODE: "hard"

SOLVER:
  IMS_PER_BATCH: 8
  STEPS: (28000,)
  MAX_ITER: 40000

INPUT:
  SAMPLING_FRAME_NUM: 6
  SAMPLING_FRAME_RANGE: 3

OUTPUT_DIR: './output_DVIS_Online_R50_OVIS_Hard'